test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  credentials:
    type: "service_account"
    project_id: "raceforum-215602"
    private_key_id: <%= Rails.application.credentials.dig(:gog, :private_key_id) %>
    private_key: <%= Rails.application.credentials.dig(:gog, :private_key).dump %>
    client_email: "raceforum@raceforum-215602.iam.gserviceaccount.com"
    client_id: "107076027661674009071"
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://accounts.google.com/o/oauth2/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/raceforum%40raceforum-215602.iam.gserviceaccount.com"
  project: "RaceForum"
  bucket: "raceforum"
